### ISSUE TITLE
Implement pluralize()

### ISSUE THREAD

**Issue by tmaly1980** [danielstjules/Stringy#154]
Having a way to pluralize words would be nice. Currently using Stringy with Laravel, and it already has a str_plural(), but I'm using Stringy for the OO chaining approach.

**Comment by danielstjules** [comment]
I'd rather keep inflector classes out of stringy, since it'd be quite a lot of work to create one that's multilingual, and many available are english-only. For example, both Laravel and its underlying Inflector are english-only: 
* https://github.com/laravel/framework/blob/9497c13bb0e22bb43db5ccde56b8354c2169003a/src/Illuminate/Support/Pluralizer.php
* https://github.com/doctrine/inflector/blob/master/lib/Doctrine/Common/Inflector/Inflector.php

May I suggest instead extending Stringy, adding any pluralize/singularize methods to the child class? :)

**Comment by hipsterjazzbo** [comment]
Had a go, see #170 :)
